### ISSUE TITLE
Can we add better readme docs?

### ISSUE THREAD

**Issue by boxman0617** [GooeyChickenman/victor#6]
I want to be able to run this locally. Can we get some basic documentation up on the readme?

**Comment by ntotolos** [comment]
There are readme's in all main directories and subdirectories that explain tooling and whatnot. I don't have any more knowledge at the moment unfortunately :(
Or is there something specific that's lacking?

**Comment by GooeyChickenman** [comment]
Whoops wrong account, but yes what my clone said ^

**Comment by GooeyChickenman** [comment]
Closin unless you had something in mind!
